'use client';

/* Ferixas service purchase flow: compact prepaid-electricity token order form using the live transaction API. */
import { useState, useEffect } from 'react';
import { Zap, Gauge } from 'lucide-react';
import { useAuth } from '@/contexts/AuthContext';
import { getServices, processTransaction } from '@/lib/services';
import TransactionPinModal from '@/components/dashboard/TransactionPinModal';

const DISCO_OPTIONS = [['ikeja-electric', 'Ikeja Electric (IKEDC)'], ['eko-electric', 'Eko Electric (EKEDC)'], ['abuja-electric', 'Abuja Electric (AEDC)'], ['ibadan-electric', 'Ibadan Electric (IBEDC)'], ['kano-electric', 'Kano Electric (KEDCO)'], ['portharcourt-electric', 'Port Harcourt Electric (PHED)'], ['jos-electric', 'Jos Electric (JED)'], ['kaduna-electric', 'Kaduna Electric (KAEDCO)'], ['enugu-electric', 'Enugu Electric (EEDC)']];
const inputClass = 'mt-2 w-full rounded-xl border border-[#E8EDF2] bg-white px-3 py-3 text-sm font-medium text-[#012044] outline-none placeholder:text-[#718096] focus:border-[#036A97] focus:ring-2 focus:ring-[#036A97]/10';

export default function ElectricityPage() {
  const { user, refreshUser } = useAuth();
  const [services, setServices] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [provider, setProvider] = useState('ikedc');
  const [meterNumber, setMeterNumber] = useState('');
  const [amount, setAmount] = useState('');
  const [showPinModal, setShowPinModal] = useState(false);
  const [processing, setProcessing] = useState(false);
  useEffect(() => { const loadServices = async () => { try { const allServices = await getServices(); const electricityService = allServices.find((item) => item.slug === 'electricity' || item.category?.toLowerCase().includes('electricity')); setServices(electricityService ? [electricityService] : allServices); } catch (loadError) { console.error('Failed to load services:', loadError); } finally { setLoading(false); } }; loadServices(); }, []);
  const handleSubmit = (event: React.FormEvent) => { event.preventDefault(); if (!user) return; if ((user.walletBalance || 0) < Number(amount)) { alert('Insufficient wallet balance.'); return; } setShowPinModal(true); };
  const onPinSuccess = async (transactionPin: string) => { if (!user) return; setProcessing(true); try { const result = await processTransaction(user.uid, Number(amount), 'electricity', { customerId: meterNumber, serviceId: provider, variationId: 'prepaid', meterNumber, transactionPin, requestId: `ELEC_${Date.now()}` }); if (result.success) { alert('Payment successful.'); setMeterNumber(''); setAmount(''); await refreshUser(); } else alert(`Transaction failed: ${result.message}`); } catch (purchaseError: any) { alert(`Error: ${purchaseError.message}`); } finally { setProcessing(false); } };
  if (loading) return <main className="mx-auto max-w-3xl"><div className="rounded-2xl border border-[#E8EDF2] bg-white p-10 text-center"><div className="mx-auto h-9 w-9 animate-spin rounded-full border-4 border-[#E8EDF2] border-t-[#036A97]" /><p className="mt-4 text-sm font-bold text-[#012044]">Loading electricity service…</p></div></main>;
  if (services.length === 0) return <main className="mx-auto max-w-3xl"><div className="rounded-2xl border border-[#F0C1B5] bg-[#FFF6F3] p-5 text-sm font-medium text-[#B3442D]">Electricity service is not available.</div></main>;
  const service = services[0];
  return <main className="mx-auto max-w-3xl space-y-5 pb-24 lg:pb-8"><section><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#718096]">Services / Electricity</p><div className="mt-2 flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#EAF5C7] text-[#416000]"><Zap size={20} /></span><div><h1 className="text-2xl font-extrabold tracking-tight text-[#012044]">Buy electricity token.</h1><p className="text-sm text-[#718096]">Choose your distributor and enter your meter number.</p></div></div></section><form onSubmit={handleSubmit} className="overflow-hidden rounded-2xl border border-[#E8EDF2] bg-white"><div className="space-y-5 p-5 sm:p-6"><div className="grid gap-4 sm:grid-cols-2"><label><span className="text-sm font-extrabold text-[#012044]">1. Electricity provider</span><select value={provider} onChange={(event) => setProvider(event.target.value)} className={inputClass}>{DISCO_OPTIONS.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label><span className="text-sm font-extrabold text-[#012044]">2. Meter number</span><span className="relative block"><Gauge size={16} className="pointer-events-none absolute left-3 top-[1.15rem] text-[#718096]" /><input type="text" value={meterNumber} onChange={(event) => setMeterNumber(event.target.value)} placeholder="Enter meter number" required className={`${inputClass} pl-9`} /></span></label></div><label className="block max-w-sm"><span className="text-sm font-extrabold text-[#012044]">3. Amount</span><input type="number" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="Enter amount" min="100" required className={inputClass} /></label><div className="flex items-center justify-between rounded-xl bg-[#FFF7F4] px-4 py-3"><span className="text-sm font-medium text-[#718096]">Wallet balance</span><span className="text-base font-extrabold text-[#012044]">₦{Number(user?.walletBalance || 0).toLocaleString()}</span></div></div><footer className="border-t border-[#E8EDF2] bg-[#FFFDFB] p-4 sm:px-6"><button type="submit" disabled={!service.is_active || processing} className="w-full rounded-xl bg-[#036A97] px-4 py-3 text-sm font-bold text-white transition hover:bg-[#012044] disabled:cursor-not-allowed disabled:opacity-40">{processing ? 'Processing payment…' : 'Buy token'}</button></footer></form><TransactionPinModal isOpen={showPinModal} onClose={() => setShowPinModal(false)} onSuccess={onPinSuccess} /></main>;
}
