import { mockApi as api } from './mockApi.js';

const app = document.querySelector('#app');
const state = { view: 'overview', selectedTicket: null, query: '', theme: 'light' };
const money = value => new Intl.NumberFormat('en-NG', { style: 'currency', currency: 'NGN', maximumFractionDigits: 0 }).format(Number(value || 0));
const compactMoney = value => value >= 1000000 ? `₦${(value / 1000000).toFixed(2)}m` : money(value);
const escape = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[char]));

const nav = [
  ['overview', 'Overview', '⌂', 'Live command center'],
  ['customers', 'Customers', '◉', 'Users, profiles & access'],
  ['wallet', 'Wallet operations', '₦', 'Credits, deposits & ledger'],
  ['activity', 'Activity & receipts', '▤', 'All customer transactions'],
  ['services', 'Service catalogue', '◇', 'VTU services & plans'],
  ['support', 'Support desk', '☏', 'Tickets & conversations'],
  ['finance', 'Financial intelligence', '↗', 'Revenue, margin & reconcile'],
  ['governance', 'Communication & audit', '◌', 'Announcements, admins & logs'],
  ['settings', 'Provider settings', '⚙', 'Providers, webhooks & controls'],
  ['profile', 'My administrator profile', '◒', 'Security & access']
];

function badge(status) {
  const normalized = String(status).toLowerCase().replace(/[^a-z]/g, '');
  const tone = ['success', 'active', 'approved', 'published', 'resolved'].includes(normalized) ? 'good' : ['pending', 'review', 'open', 'inprogress', 'maintenance'].includes(normalized) ? 'warn' : ['failed', 'suspended', 'rejected'].includes(normalized) ? 'bad' : 'neutral';
  return `<span class="badge ${tone}"><i></i>${escape(String(status).replace('_', ' '))}</span>`;
}
function initials(name) { return String(name).split(' ').map(part => part[0]).slice(0, 2).join('').toUpperCase(); }
function iconCircle(symbol, tone = '') { return `<span class="icon-circle ${tone}">${symbol}</span>`; }
function empty(title, description, action = '') { return `<div class="empty"><div>${iconCircle('⌁')}</div><h3>${title}</h3><p>${description}</p>${action}</div>`; }
function toast(title, copy, tone = 'good') { const region = document.querySelector('#toast-region'); const node = document.createElement('div'); node.className = `toast ${tone}`; node.innerHTML = `<b>${escape(title)}</b><span>${escape(copy)}</span>`; region.appendChild(node); setTimeout(() => node.remove(), 3700); }
function drawer(title, content, actions = '') { document.querySelector('#overlay')?.remove(); const node = document.createElement('div'); node.id = 'overlay'; node.className = 'overlay'; node.innerHTML = `<section class="drawer" role="dialog" aria-modal="true"><header><div><span class="eyebrow">FERIXAS OPERATIONS</span><h2>${title}</h2></div><button class="icon-button close-overlay" aria-label="Close">×</button></header><div class="drawer-body">${content}</div>${actions ? `<footer class="drawer-actions">${actions}</footer>` : ''}</section>`; document.body.appendChild(node); node.addEventListener('click', event => { if (event.target === node || event.target.closest('.close-overlay')) node.remove(); }); }
function setView(view) { state.view = view; state.query = ''; render(); }

function shell(content, title, subtitle) {
  return `<div class="app-shell">
    <aside class="sidebar">
      <button class="brand" data-nav="overview"><img src="./assets/ferixas-globe.png" alt="Ferixas"/><span><b>Ferixas</b><small>AsaforVTU operations</small></span></button>
      <div class="workspace"><span>OPERATIONS WORKSPACE</span><button class="workspace-switch">Nigeria production <i>⌄</i></button></div>
      <nav class="side-nav">${nav.map(([key, label, icon, helper]) => `<button class="nav-item ${state.view === key ? 'active' : ''}" data-nav="${key}"><i>${icon}</i><span>${label}<small>${helper}</small></span></button>`).join('')}</nav>
      <div class="sidebar-footer"><div class="admin-mini"><span>FO</span><div><b>Ferixas Operations</b><small>Super administrator</small></div><i>⋮</i></div><button class="signout" data-action="signout">⇥ Sign out prototype</button></div>
    </aside>
    <main class="main">
      <header class="topbar">
        <button class="mobile-menu" data-action="mobile-menu">☰</button>
        <label class="search"><span>⌕</span><input id="global-search" placeholder="Search customers, references, tickets…" value="${escape(state.query)}"/></label>
        <div class="top-actions"><button class="env-chip" title="Prototype data only"><i></i> Simulator mode</button><button class="icon-button" data-action="notifications" aria-label="Notifications">♢<em></em></button><button class="avatar-button" data-nav="profile">FO</button></div>
      </header>
      <section class="content"><div class="page-title"><div><span class="eyebrow">OPERATIONS COMMAND</span><h1>${title}</h1><p>${subtitle}</p></div><div class="page-actions">${viewActions()}</div></div>${content}</section>
    </main>
  </div>`;
}
function viewActions() {
  const actions = {
    overview: `<button class="button secondary" data-action="export">⇩ Export report</button><button class="button primary" data-nav="wallet">＋ Wallet operation</button>`,
    customers: `<button class="button secondary" data-action="export">⇩ Export customers</button><button class="button primary" data-action="create-user">＋ Create customer</button>`,
    wallet: `<button class="button secondary" data-action="reconcile">↻ Reconcile payment</button><button class="button primary" data-action="credit-wallet">＋ Credit wallet</button>`,
    activity: `<button class="button secondary" data-action="export">⇩ Export activity</button><button class="button primary" data-action="reconcile">↻ Reconcile payment</button>`,
    services: `<button class="button secondary" data-action="sync-plans">↻ Sync provider plans</button><button class="button primary" data-action="create-service">＋ Add service</button>`,
    support: `<button class="button secondary" data-action="filter-tickets">⌄ Filter queue</button><button class="button primary" data-action="new-ticket">＋ Create ticket</button>`,
    finance: `<button class="button secondary" data-action="export">⇩ Export financials</button><button class="button primary" data-action="reconcile">↻ Reconcile payment</button>`,
    governance: `<button class="button secondary" data-action="create-admin">＋ Add admin</button><button class="button primary" data-action="create-announcement">＋ New announcement</button>`,
    settings: `<button class="button primary" data-action="save-settings">Save changes</button>`,
    profile: `<button class="button primary" data-action="save-profile">Save profile</button>`
  };
  return actions[state.view] || '';
}

async function overview() {
  const data = await api.getOverview();
  return shell(`<section class="metric-grid">
      ${metric('Network volume', compactMoney(data.todayVolume), '+12.4%', '↑', 'blue')}
      ${metric('System wallet balance', compactMoney(data.mainBalance), 'Across all customer wallets', '₦', 'navy')}
      ${metric('Active customers', data.activeUsers.toLocaleString(), `${data.totalUsers - data.activeUsers} require attention`, '◉', 'mint')}
      ${metric('Success rate', `${data.successRate}%`, 'Provider-reported completion rate', '✓', 'lime')}
    </section>
    <section class="command-grid">
      <article class="hero-card"><div class="hero-card-head"><div><span class="eyebrow on-dark">TODAY’S OPERATING PICTURE</span><h2>Balanced, with two items needing review.</h2></div>${badge('live')}</div><div class="sparkline"><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span><svg viewBox="0 0 700 160" preserveAspectRatio="none"><path d="M0 130 C40 116 65 120 100 93 S165 120 205 68 S279 86 325 55 S392 81 440 42 S517 80 570 36 S650 48 700 10" fill="none" stroke="#baf039" stroke-width="4"/><path d="M0 130 C40 116 65 120 100 93 S165 120 205 68 S279 86 325 55 S392 81 440 42 S517 80 570 36 S650 48 700 10 L700 160 L0 160Z" fill="url(#area)"/><defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop stop-color="#baf039" stop-opacity=".32"/><stop offset="1" stop-color="#baf039" stop-opacity="0"/></linearGradient></defs></svg></div><div class="hero-stats"><div><b>₦385,400</b><small>processed today</small></div><div><b>1,972</b><small>requests handled</small></div><div><b>02</b><small>review items</small></div></div></article>
      <article class="attention-card"><div><span class="eyebrow">ATTENTION QUEUE</span><h2>Resolve the flow blockers.</h2></div><button class="attention-item" data-nav="support"><span>${iconCircle('☏','orange')}</span><div><b>1 high-priority support request</b><small>SUP-4827 · Data purchase pending</small></div><i>›</i></button><button class="attention-item" data-nav="wallet"><span>${iconCircle('₦','blue')}</span><div><b>${data.pendingDeposits} deposit reviews</b><small>Payment verification needed</small></div><i>›</i></button><button class="attention-item" data-nav="services"><span>${iconCircle('ϟ','lime')}</span><div><b>Electricity service maintenance</b><small>Customer notice is recommended</small></div><i>›</i></button></article>
    </section>
    <section class="split-grid"><article class="panel"><header class="panel-head"><div><span class="eyebrow">LIVE ACTIVITY</span><h2>Latest customer activity</h2></div><button class="text-button" data-nav="activity">View all →</button></header>${data.recent.map(row => activityRow(row)).join('')}</article><article class="panel"><header class="panel-head"><div><span class="eyebrow">OPERATING SIGNALS</span><h2>System notifications</h2></div><button class="text-button" data-action="notifications">Mark all read</button></header>${data.alerts.slice(0,3).map(notificationRow).join('')}</article></section>`, 'Good evening, Operations.', 'A live overview of customer activity, service health, and actions that need attention.');
}
function metric(label, value, caption, symbol, tone) { return `<article class="metric ${tone}"><span>${symbol}</span><div><small>${label}</small><b>${value}</b><p>${caption}</p></div></article>`; }
function activityRow(row) { return `<button class="activity-row" data-action="transaction" data-id="${row.id}"><span>${iconCircle(row.type.includes('credit') ? '↓' : row.type.includes('pending') ? '…' : '↑', row.status)}</span><div><b>${escape(row.type)}</b><small>${escape(row.user)} · ${escape(row.channel)} · ${escape(row.time)}</small></div><div class="row-amount"><b>${money(row.amount)}</b>${badge(row.status)}</div><i>›</i></button>`; }
function notificationRow(item) { return `<article class="notification-row"><span class="notification-dot ${item.unread ? 'unread' : ''}"></span><div><b>${escape(item.title)}</b><p>${escape(item.body)}</p><small>${escape(item.time)}</small></div></article>`; }

async function customers() { const users = await api.listUsers(); const filtered = users.filter(user => `${user.name} ${user.email} ${user.username}`.toLowerCase().includes(state.query.toLowerCase())); return shell(`<section class="toolbar"><div class="segmented"><button class="active">All customers <span>${users.length}</span></button><button>Active <span>${users.filter(u=>u.status==='active').length}</span></button><button>Suspended <span>${users.filter(u=>u.status==='suspended').length}</span></button></div><div><button class="filter">⌄ Status</button><button class="filter">⌄ Verification</button></div></section><article class="table-panel"><table><thead><tr><th>Customer</th><th>Wallet balance</th><th>Transactions</th><th>Verification</th><th>Last sign in</th><th>Status</th><th></th></tr></thead><tbody>${filtered.map(user => `<tr><td><button class="user-cell" data-action="user" data-id="${user.id}"><span class="user-avatar">${initials(user.name)}</span><div><b>${escape(user.name)}</b><small>@${escape(user.username)} · ${escape(user.email)}</small></div></button></td><td><b>${money(user.balance)}</b></td><td>${user.transactions}</td><td>${badge(user.verified ? 'verified' : 'unverified')}</td><td>${escape(user.lastLogin)}</td><td>${badge(user.status)}</td><td><button class="kebab" data-action="user" data-id="${user.id}">•••</button></td></tr>`).join('')}</tbody></table></article>`, 'Customer directory', 'Manage identities, wallets, verification, account access, profiles, referrals, and customer activity.'); }

async function wallet() { const [deposits, users, logs] = await Promise.all([api.listDeposits(), api.listUsers(), api.listLogs()]); return shell(`<section class="metric-grid wallet-metrics">${metric('Pending review', deposits.filter(d => d.status !== 'approved').length, 'Wallet credit requests to decide', '◌', 'orange')}${metric('Manual credits today', money(5000), 'Recorded with receipt events', '↓', 'blue')}${metric('Ledger health', 'Healthy', 'No unmatched wallet entries', '✓', 'lime')}${metric('Ghost-wallet scan', 'Ready', 'Safe dry-run available', '⌁', 'navy')}</section><section class="split-grid wide-left"><article class="panel"><header class="panel-head"><div><span class="eyebrow">FUNDING REVIEW</span><h2>Deposit requests</h2></div><button class="text-button" data-action="credit-wallet">Manual credit →</button></header><div class="deposit-list">${deposits.map(deposit => `<article class="deposit-row"><div><span class="deposit-ref">${deposit.id}</span><b>${escape(deposit.user)}</b><small>${escape(deposit.method)} · ${escape(deposit.time)}</small></div><div><b>${money(deposit.amount)}</b>${badge(deposit.status)}</div>${deposit.status !== 'approved' ? `<div class="inline-actions"><button class="mini good" data-action="deposit" data-id="${deposit.id}" data-status="approved">Approve</button><button class="mini danger" data-action="deposit" data-id="${deposit.id}" data-status="rejected">Reject</button></div>` : '<span class="receipt-ready">Receipt ready</span>'}</article>`).join('')}</div></article><article class="panel credit-panel"><span class="eyebrow">DIRECT WALLET ACTION</span><h2>Credit a customer</h2><p>Creates a ledger entry, customer notification, transaction activity, and receipt record in the live implementation.</p><form id="quick-credit"><label>Customer<select name="userId">${users.map(u => `<option value="${u.id}">${escape(u.name)} · ${u.id}</option>`).join('')}</select></label><label>Amount<input name="amount" type="number" min="1" value="1000" /></label><label>Reason<input name="note" value="Manual operations credit" /></label><button class="button primary" type="submit">Credit wallet →</button></form></article></section><section class="panel"><header class="panel-head"><div><span class="eyebrow">WALLET AUDIT</span><h2>Recent ledger controls</h2></div><button class="text-button" data-action="fix-ghosts">Run safe ghost-wallet scan →</button></header>${logs.map(log => `<div class="audit-row"><span class="log-level ${log.level.toLowerCase()}">${log.level}</span><b>${escape(log.event)}</b><span>${escape(log.entity)}</span><span>${escape(log.actor)}</span><small>${escape(log.time)}</small></div>`).join('')}</section>`, 'Wallet operations', 'Review customer funding, make audited credits or debits, reconcile payments, and monitor ledger integrity.'); }

async function activity() { const transactions = await api.listTransactions(); return shell(`<section class="toolbar"><div class="segmented"><button class="active">All activity</button><button>Successful</button><button>Pending</button><button>Failed</button></div><div><button class="filter">⌄ Service</button><button class="filter">⌄ Date range</button></div></section><article class="table-panel"><table><thead><tr><th>Reference</th><th>Customer</th><th>Operation</th><th>Channel</th><th>Amount</th><th>Time</th><th>Status</th><th></th></tr></thead><tbody>${transactions.map(row => `<tr><td><button class="ref" data-action="transaction" data-id="${row.id}">${escape(row.reference)}</button></td><td>${escape(row.user)}</td><td>${escape(row.type)}</td><td>${escape(row.channel)}</td><td><b>${money(row.amount)}</b></td><td>${escape(row.time)}</td><td>${badge(row.status)}</td><td><button class="kebab" data-action="transaction" data-id="${row.id}">•••</button></td></tr>`).join('')}</tbody></table></article><section class="receipt-note">Every row is designed to resolve to a transaction detail page with provider response, wallet impact, customer notification status, reconciliation actions, and downloadable receipt data.</section>`, 'Activity & receipts', 'Trace every wallet event and service request from customer action to provider result, ledger movement, notification, and receipt.'); }

async function services() { const [services, plans] = await Promise.all([api.listServices(), api.listPlans()]); return shell(`<section class="service-grid">${services.map(service => `<article class="service-card"><div class="service-icon">${service.icon}</div><div class="service-card-title"><span>${badge(service.state)}</span><button class="kebab" data-action="service" data-id="${service.id}">•••</button></div><h2>${escape(service.name)}</h2><p>${escape(service.category)} service · ${service.plans} configured plans</p><div class="service-meta"><span>Margin <b>${service.margin}</b></span><span>State <b>${escape(service.state)}</b></span></div><button class="line-action" data-action="service" data-id="${service.id}">Configure service <i>→</i></button></article>`).join('')}</section><article class="table-panel plans-table"><header class="panel-head"><div><span class="eyebrow">PRICING CATALOGUE</span><h2>Service plans & provider margin</h2></div><button class="text-button" data-action="create-plan">＋ Add plan</button></header><table><thead><tr><th>Plan</th><th>Service</th><th>Network</th><th>Provider price</th><th>Customer price</th><th>Margin</th><th>Status</th><th></th></tr></thead><tbody>${plans.map(plan => `<tr><td><b>${escape(plan.name)}</b></td><td>${escape(plan.service)}</td><td>${escape(plan.network)}</td><td>${money(plan.providerPrice)}</td><td><b>${money(plan.customerPrice)}</b></td><td class="positive">${money(plan.customerPrice-plan.providerPrice)}</td><td>${badge(plan.state)}</td><td><button class="kebab" data-action="plan" data-id="${plan.id}">•••</button></td></tr>`).join('')}</tbody></table></article>`, 'Service catalogue', 'Configure every customer-facing VTU service, price plan, provider mapping, availability status, and margin.'); }

async function support() { const tickets = await api.listTickets(); const selected = tickets.find(ticket => ticket.id === state.selectedTicket) || tickets[0]; state.selectedTicket = selected?.id || null; return shell(`<section class="support-layout"><aside class="ticket-list"><header><span class="eyebrow">QUEUE</span><h2>${tickets.filter(t=>t.status!=='resolved').length} active conversations</h2><div class="queue-filters"><button class="active">All</button><button>Open</button><button>In progress</button><button>Resolved</button></div></header>${tickets.map(ticket => `<button class="ticket-card ${ticket.id === selected.id ? 'selected' : ''}" data-action="select-ticket" data-id="${ticket.id}"><div><span>${badge(ticket.status)}</span>${ticket.priority === 'high' ? '<span class="priority">HIGH</span>' : ''}</div><b>${escape(ticket.subject)}</b><small>${escape(ticket.id)} · ${escape(ticket.user)}</small><time>${escape(ticket.updated)}</time></button>`).join('')}</aside><article class="conversation"><header><div><span class="eyebrow">${escape(selected.id)} · ${escape(selected.priority)} priority</span><h2>${escape(selected.subject)}</h2><p>${escape(selected.user)} · ${badge(selected.status)}</p></div><div><button class="filter" data-action="ticket-status">${selected.status} ⌄</button><button class="icon-button">•••</button></div></header><div class="messages">${selected.messages.map(message => `<article class="message ${message.role}"><span>${message.role === 'admin' ? 'FO' : initials(selected.user)}</span><div><b>${escape(message.from)}</b><p>${escape(message.text)}</p><small>${escape(message.time)}</small></div></article>`).join('')}</div><form id="ticket-reply" class="reply-box"><textarea name="reply" placeholder="Write an operations reply…"></textarea><div><button type="button" class="attachment">⌇ Attach evidence</button><button class="button primary" type="submit">Send reply →</button></div></form></article><aside class="ticket-context"><span class="eyebrow">CUSTOMER CONTEXT</span><div class="profile-block"><span class="user-avatar large">${initials(selected.user)}</span><h3>${escape(selected.user)}</h3><p>Verified customer · Active wallet</p><button class="line-action" data-nav="customers">Open customer profile <i>→</i></button></div><dl><div><dt>Wallet balance</dt><dd>₦5,000</dd></div><div><dt>Open tickets</dt><dd>1</dd></div><div><dt>Last transaction</dt><dd>Today, 16:28</dd></div><div><dt>Notification</dt><dd>Delivered</dd></div></dl></aside></section>`, 'Support desk', 'Handle the real customer conversation, ticket status, context, attachments, and every support notification from one operational view.'); }

async function finance() { return shell(`<section class="finance-hero"><div><span class="eyebrow on-dark">FINANCIAL INTELLIGENCE</span><h2>Know what entered, moved, completed, and needs reconciliation.</h2><p>This information architecture maps to system finance, customer finance, payment reconciliation, deposits, wallet audit logs, and transaction detail endpoints.</p><div class="finance-hero-stats"><span><b>₦3.28m</b> 30-day revenue</span><span><b>₦165k</b> estimated margin</span><span><b>97.8%</b> completion</span></div></div><div class="finance-orbit"><span>₦</span><i></i><i></i><i></i></div></section><section class="metric-grid finance-cards">${metric('Gross volume', '₦3.28m', 'Last 30 days', '↗', 'blue')}${metric('Provider cost', '₦3.11m', 'Service procurement', '⇄', 'navy')}${metric('Estimated margin', '₦165k', 'Across completed requests', '◒', 'lime')}${metric('Reconciliation', '2 items', 'Pending provider checks', '↻', 'orange')}</section><section class="split-grid"><article class="panel"><header class="panel-head"><div><span class="eyebrow">VOLUME TREND</span><h2>Transaction volume</h2></div><select><option>Last 30 days</option></select></header><div class="bar-chart">${[42, 63, 51, 78, 59, 92, 81, 68, 97, 75, 86, 108].map((height, index) => `<div><i style="height:${height}px"></i><small>${index % 2 ? '' : index + 1}</small></div>`).join('')}</div></article><article class="panel"><header class="panel-head"><div><span class="eyebrow">RECONCILIATION</span><h2>Provider exceptions</h2></div><button class="text-button" data-action="reconcile">Check reference →</button></header><div class="exception"><span>${iconCircle('↻','orange')}</span><div><b>TXN-6C1Q8</b><p>Electricity request is pending provider confirmation.</p></div>${badge('review')}</div><div class="exception"><span>${iconCircle('₦','blue')}</span><div><b>DEP-002</b><p>Wallet funding needs verification before approval.</p></div>${badge('pending')}</div></article></section>`, 'Financial intelligence', 'Use actual financial data to monitor service volume, margin, customer funding, system balances, provider cost, and reconciliation exceptions.'); }

async function governance() { const [announcements, admins, logs] = await Promise.all([api.listAnnouncements(), api.listAdmins(), api.listLogs()]); return shell(`<section class="governance-grid"><article class="panel"><header class="panel-head"><div><span class="eyebrow">CUSTOMER COMMUNICATION</span><h2>Published announcements</h2></div><button class="text-button" data-action="create-announcement">＋ New</button></header>${announcements.map(item => `<article class="announcement-row"><span>${iconCircle('◌','blue')}</span><div><b>${escape(item.title)}</b><p>${escape(item.content)}</p><small>${escape(item.audience)} · ${escape(item.created)}</small></div>${badge(item.state)}</article>`).join('')}</article><article class="panel"><header class="panel-head"><div><span class="eyebrow">ACCESS GOVERNANCE</span><h2>Administrator accounts</h2></div><button class="text-button" data-action="create-admin">＋ Add admin</button></header>${admins.map(admin => `<article class="admin-row"><span class="user-avatar">${initials(admin.name)}</span><div><b>${escape(admin.name)}</b><p>${escape(admin.email)} · ${escape(admin.role)}</p></div><small>${escape(admin.lastActive)}</small></article>`).join('')}</article></section><article class="panel audit-panel"><header class="panel-head"><div><span class="eyebrow">AUDIT TRAIL</span><h2>Recent administrative events</h2></div><button class="text-button" data-nav="profile">Access policy →</button></header>${logs.map(log => `<div class="audit-row"><span class="log-level ${log.level.toLowerCase()}">${escape(log.level)}</span><b>${escape(log.event)}</b><span>${escape(log.entity)}</span><span>${escape(log.actor)}</span><small>${escape(log.time)}</small></div>`).join('')}</article>`, 'Communication & audit', 'Publish customer notices, manage administrator access, inspect audit events, and preserve operational accountability.'); }

function settings() { return Promise.resolve(shell(`<section class="settings-layout"><article class="settings-nav"><span class="eyebrow">CONFIGURATION</span><button class="active">Provider connections</button><button>Webhook security</button><button>Notification policy</button><button>Referral settings</button><button>Feature availability</button></article><section><article class="panel settings-card"><span class="eyebrow">PROVIDER CONNECTIONS</span><h2>Connect the services that fulfil customer requests.</h2><p>These controls represent the existing API settings and provider endpoints. The implementation layer binds these form values to live provider configuration rather than keeping them as UI-only data.</p><div class="provider-config"><div><span class="provider-mark">V</span><b>VTpass service provider</b>${badge('connected')}</div><button class="button secondary">Test connection</button></div><div class="provider-config"><div><span class="provider-mark">F</span><b>Flutterwave payment provider</b>${badge('connected')}</div><button class="button secondary">Test connection</button></div><div class="provider-config"><div><span class="provider-mark">M</span><b>Mail delivery provider</b>${badge('review')}</div><button class="button secondary">Configure</button></div></article><article class="panel settings-card"><span class="eyebrow">WEBHOOK SECURITY</span><h2>Flutterwave payment callback</h2><label>Webhook URL<input readonly value="https://vtuapi.ferixas.com/api/webhooks/flutterwave" /></label><label>Verification secret<input type="password" value="••••••••••••••" /></label><p class="field-note">Verification is enforced before a payment can change wallet balance or notify a customer.</p></article></section></section>`, 'Provider settings', 'Manage provider connections, webhook protection, notification policy, referral reward configuration, and system-level availability.'));
}
function profile() { return Promise.resolve(shell(`<section class="profile-layout"><article class="profile-card"><span class="profile-badge">FO</span><span class="eyebrow">SIGNED-IN ADMINISTRATOR</span><h2>Ferixas Operations</h2><p>Super administrator · ops@ferixas.com</p><div><span>Last signed in <b>Today, 17:48</b></span><span>Two-factor status <b class="positive">Enabled</b></span><span>Assigned workspace <b>Nigeria production</b></span></div></article><article class="panel profile-form"><span class="eyebrow">PROFILE & SECURITY</span><h2>Administrator settings</h2><div class="form-grid"><label>Full name<input value="Ferixas Operations" /></label><label>Role<input readonly value="Super administrator" /></label><label>Work email<input value="ops@ferixas.com" /></label><label>Phone number<input value="+234 803 000 0000" /></label></div><hr/><h3>Security controls</h3><div class="security-row"><div><b>Two-factor authentication</b><p>Require a second verification step for sensitive operations.</p></div><button class="toggle on"><i></i></button></div><div class="security-row"><div><b>Approval confirmation</b><p>Confirm manual credits and account access changes before submission.</p></div><button class="toggle on"><i></i></button></div></article></section>`, 'My administrator profile', 'Manage administrator identity, authentication controls, access preferences, and the confirmation policies used for sensitive operations.'));
}

const views = { overview, customers, wallet, activity, services, support, finance, governance, settings, profile };
async function render() { app.innerHTML = `<div class="loading-screen"><span class="loader"></span></div>`; const view = views[state.view] || overview; app.innerHTML = await view(); wire(); }

function wire() {
  app.querySelectorAll('[data-nav]').forEach(button => button.addEventListener('click', () => setView(button.dataset.nav)));
  const search = app.querySelector('#global-search'); if (search) search.addEventListener('input', event => { state.query = event.target.value; if (state.view === 'customers') render(); });
  app.querySelectorAll('[data-action]').forEach(button => button.addEventListener('click', () => action(button.dataset.action, button.dataset)));
  app.querySelector('#quick-credit')?.addEventListener('submit', async event => { event.preventDefault(); const form = new FormData(event.currentTarget); const user = await api.creditWallet(form.get('userId'), form.get('amount'), form.get('note')); toast('Wallet credited', `${user.name} now has ${money(user.balance)}.`, 'good'); render(); });
  app.querySelector('#ticket-reply')?.addEventListener('submit', async event => { event.preventDefault(); const text = new FormData(event.currentTarget).get('reply')?.trim(); if (!text) return toast('Reply required', 'Write a message before sending.', 'warn'); await api.replyTicket(state.selectedTicket, text); toast('Reply stored', 'The simulated customer conversation and notification have both updated.', 'good'); render(); });
}
async function action(name, data = {}) {
  if (name === 'notifications') { const notifications = await api.listNotifications(); drawer('Operations notifications', notifications.map(notificationRow).join(''), `<button class="button secondary" id="mark-read">Mark all read</button>`); document.querySelector('#mark-read')?.addEventListener('click', async () => { await api.markNotificationsRead(); document.querySelector('#overlay').remove(); toast('Notifications updated', 'All simulated alerts are marked as read.', 'good'); render(); }); }
  if (name === 'user') { const user = (await api.listUsers()).find(item => item.id === data.id); drawer(user.name, `<div class="drawer-profile"><span class="user-avatar huge">${initials(user.name)}</span><div><h3>${escape(user.name)}</h3><p>@${escape(user.username)} · ${escape(user.email)}</p>${badge(user.status)}</div></div><dl class="detail-list"><div><dt>Customer ID</dt><dd>${user.id}</dd></div><div><dt>Wallet balance</dt><dd>${money(user.balance)}</dd></div><div><dt>Phone</dt><dd>${user.phone}</dd></div><div><dt>Referral code</dt><dd>${user.referralCode}</dd></div><div><dt>Transactions</dt><dd>${user.transactions}</dd></div><div><dt>Verification</dt><dd>${user.verified ? 'Verified' : 'Unverified'}</dd></div></dl>`, `<button class="button secondary" id="toggle-user">${user.status === 'active' ? 'Suspend account' : 'Activate account'}</button><button class="button primary" id="drawer-credit">Credit wallet</button>`); document.querySelector('#toggle-user')?.addEventListener('click', async () => { await api.updateUser(user.id, { status: user.status === 'active' ? 'suspended' : 'active' }); toast('Account updated', `${user.name} is now ${user.status === 'active' ? 'suspended' : 'active'}.`, 'warn'); document.querySelector('#overlay').remove(); render(); }); document.querySelector('#drawer-credit')?.addEventListener('click', () => creditDrawer(user)); }
  if (name === 'credit-wallet') creditDrawer();
  if (name === 'deposit') { await api.updateDeposit(data.id, data.status); toast(`Deposit ${data.status}`, `${data.id} has been updated with a simulated audit event.`, data.status === 'approved' ? 'good' : 'warn'); render(); }
  if (name === 'transaction') { const row = (await api.listTransactions()).find(item => item.id === data.id || item.reference === data.id); if (row) drawer(`Receipt · ${row.reference}`, `<div class="receipt"><span class="receipt-status">${badge(row.status)}</span><h3>${money(row.amount)}</h3><p>${escape(row.type)} for ${escape(row.user)}</p><dl class="detail-list"><div><dt>Transaction ID</dt><dd>${row.id}</dd></div><div><dt>Reference</dt><dd>${row.reference}</dd></div><div><dt>Provider / channel</dt><dd>${row.channel}</dd></div><div><dt>Created</dt><dd>${row.time}</dd></div><div><dt>Notification</dt><dd>Delivered</dd></div></dl></div>`, `<button class="button secondary" id="reconcile-one">Reconcile payment</button><button class="button primary">Download receipt</button>`); document.querySelector('#reconcile-one')?.addEventListener('click', () => action('reconcile', { reference: row.reference })); }
  if (name === 'reconcile') { drawer('Reconcile provider payment', `<p class="modal-copy">Check the authoritative payment provider outcome before marking a wallet funding or service transaction successful.</p><label>Reference or transaction ID<input id="reconcile-ref" value="${data.reference || 'TXN-6C1Q8'}" /></label><p class="field-note">The live adapter will call the existing administrator payment reconciliation endpoint.</p>`, `<button class="button primary" id="submit-reconcile">Check provider status →</button>`); document.querySelector('#submit-reconcile')?.addEventListener('click', async () => { const ref = document.querySelector('#reconcile-ref').value; const result = await api.reconcile(ref); toast('Reconciliation complete', `${ref} resolved as ${result.status}.`, result.status === 'success' ? 'good' : 'warn'); document.querySelector('#overlay').remove(); render(); }); }
  if (name === 'select-ticket') { state.selectedTicket = data.id; render(); }
  if (name === 'ticket-status') { const current = (await api.listTickets()).find(item => item.id === state.selectedTicket); drawer('Update support status', `<label>Ticket status<select id="ticket-status-select"><option ${current.status==='open'?'selected':''}>open</option><option ${current.status==='in_progress'?'selected':''}>in_progress</option><option ${current.status==='resolved'?'selected':''}>resolved</option></select></label><p class="field-note">Changing status creates a customer support notification in the live implementation.</p>`, `<button id="save-ticket-status" class="button primary">Update status</button>`); document.querySelector('#save-ticket-status')?.addEventListener('click', async () => { const status = document.querySelector('#ticket-status-select').value; await api.updateTicket(current.id, status); document.querySelector('#overlay').remove(); toast('Ticket updated', `${current.id} is now ${status}.`, 'good'); render(); }); }
  if (name === 'service') { const service = (await api.listServices()).find(item => item.id === data.id); drawer(`Configure ${service.name}`, `<div class="form-grid"><label>Service name<input value="${escape(service.name)}" /></label><label>Category<input value="${escape(service.category)}" /></label><label>Availability<select id="service-state"><option ${service.state==='active'?'selected':''}>active</option><option ${service.state==='maintenance'?'selected':''}>maintenance</option><option ${service.state==='disabled'?'selected':''}>disabled</option></select></label><label>Margin<input value="${escape(service.margin)}" /></label></div><p class="field-note">The future live adapter maps directly to create/update/delete service endpoints and keeps this screen’s contract unchanged.</p>`, `<button class="button primary" id="save-service">Save service</button>`); document.querySelector('#save-service')?.addEventListener('click', async () => { await api.updateService(service.id, { state: document.querySelector('#service-state').value }); document.querySelector('#overlay').remove(); toast('Service updated', `${service.name} configuration is saved in the prototype.`, 'good'); render(); }); }
  if (name === 'create-announcement') announcementDrawer();
  if (name === 'create-user' || name === 'new-ticket' || name === 'create-service' || name === 'create-plan' || name === 'create-admin') genericCreateDrawer(name);
  if (name === 'sync-plans') { toast('Provider sync queued', 'The prototype queued a plan synchronization using the live adapter contract.', 'good'); }
  if (name === 'fix-ghosts') { toast('Safe scan complete', 'No changes were made. The live adapter defaults to a dry run.', 'good'); }
  if (name === 'save-settings' || name === 'save-profile') toast('Prototype settings saved', 'The live adapter will submit these exact settings to the production backend.', 'good');
  if (name === 'export') toast('Export prepared', 'A real implementation will generate this from the selected endpoint and filters.', 'good');
  if (name === 'filter-tickets') toast('Queue filters', 'Filter controls are included in the integration map.', 'good');
  if (name === 'signout') toast('Prototype session retained', 'This standalone preview does not use production authentication.', 'warn');
}
async function creditDrawer(defaultUser) { const users = await api.listUsers(); drawer('Credit customer wallet', `<p class="modal-copy">This operation produces a wallet ledger entry, transaction activity, receipt data, and customer notification.</p><form id="credit-form"><label>Customer<select name="userId">${users.map(user => `<option value="${user.id}" ${defaultUser?.id === user.id ? 'selected' : ''}>${escape(user.name)} · ${user.id}</option>`).join('')}</select></label><label>Amount<input name="amount" type="number" min="1" value="1000" /></label><label>Reason<input name="note" value="Manual operations credit" /></label></form>`, `<button class="button primary" id="submit-credit">Confirm credit →</button>`); document.querySelector('#submit-credit')?.addEventListener('click', async () => { const form = new FormData(document.querySelector('#credit-form')); const user = await api.creditWallet(form.get('userId'), form.get('amount'), form.get('note')); document.querySelector('#overlay').remove(); toast('Wallet credited', `${user.name} has been notified and the receipt is available.`, 'good'); render(); }); }
function announcementDrawer() { drawer('Publish customer announcement', `<form id="announcement-form"><label>Announcement title<input name="title" placeholder="e.g. Scheduled service update" /></label><label>Customer message<textarea name="content" placeholder="Explain the service update clearly and briefly."></textarea></label><label>Audience<select name="audience"><option>All users</option><option>Active users</option><option>Users with pending transactions</option></select></label></form>`, `<button id="publish-announcement" class="button primary">Publish announcement →</button>`); document.querySelector('#publish-announcement')?.addEventListener('click', async () => { const form = new FormData(document.querySelector('#announcement-form')); if (!form.get('title') || !form.get('content')) return toast('Incomplete announcement', 'A title and customer message are required.', 'warn'); await api.createAnnouncement(Object.fromEntries(form)); document.querySelector('#overlay').remove(); toast('Announcement published', 'The customer notification and dashboard announcement are simulated.', 'good'); render(); }); }
function genericCreateDrawer(name) { const labels = { 'create-user':'Create customer', 'new-ticket':'Create support ticket', 'create-service':'Add service', 'create-plan':'Add service plan', 'create-admin':'Add administrator' }; drawer(labels[name], `<p class="modal-copy">This prototype includes the complete operation. During integration, this form connects to the existing administrative API method with the same validation and error response behavior.</p><div class="form-grid"><label>Name<input placeholder="Enter a name" /></label><label>Email or identifier<input placeholder="Enter email or ID" /></label><label>Notes<textarea placeholder="Optional operational note"></textarea></label></div>`, `<button class="button primary close-overlay">Save in prototype</button>`); }

render();
