"use client";

import { Bell, CheckCircle2, ChevronRight, Copy, Gift, GraduationCap, Phone, ReceiptText, WalletCards, Wifi, Tv, Zap } from "lucide-react";

type Props = { wallet: any; transactions: any[]; services: any[]; announcement?: any; navigate: (path: string) => void };
const money = (value: number) => `₦${Number(value || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const icons: Record<string, any> = { airtime: Phone, data: Wifi, cable: Tv, electricity: Zap, "exam-pins": GraduationCap };

function Tag({ children }: { children: React.ReactNode }) { return <span className="asf-tag"><i />{children}</span>; }
function Balance({ label, value, icon: Icon }: { label: string; value: number; icon: any }) { return <article className="balance-mini"><Icon size={20} /><small>{label}</small><b>{money(value)}</b></article>; }
function TxRow({ tx, onClick }: { tx: any; onClick: () => void }) { const credit = String(tx.type).toLowerCase() === "credit"; return <button className="tx-row" onClick={onClick}><span className={`tx-icon ${credit ? "credit" : "debit"}`}>{credit ? <CheckCircle2 size={16} /> : <ReceiptText size={16} />}</span><div><b>{tx.service || tx.type || "Transaction"}</b><small>{tx.created_at ? new Date(tx.created_at).toLocaleString() : ""} · {tx.reference || tx.transaction_ref || "Reference pending"}</small></div><Tag>{tx.status || "processing"}</Tag><strong className={credit ? "credit" : "debit"}>{credit ? "+" : "−"}{money(tx.amount)}</strong><ChevronRight size={16} /></button>; }

export default function ApprovedLiveDashboardHome({ wallet, transactions, services, announcement, navigate }: Props) {
  const availableServices = services.filter(service => icons[service.slug]).slice(0, 5);
  return <div className="page"><>{announcement && <section className="announcement announcement--available" aria-live="polite"><span className="announcement-icon"><Bell /></span><div><b>{announcement.title}</b><p>{announcement.content}</p></div><span className="announcement-controls"><i className="active" /></span></section>}</><div className="overview-grid"><section className="wallet-hero"><span className="wallet-orbit wallet-orbit--one" /><span className="wallet-orbit wallet-orbit--two" /><span className="wallet-leaf wallet-leaf--one" /><span className="wallet-leaf wallet-leaf--two" /><span className="wallet-spark wallet-spark--one" /><span className="wallet-spark wallet-spark--two" /><header><span>WALLET BALANCE</span><Tag>Verified</Tag></header><div><b>{money(wallet.main_balance)}</b></div><p>Main wallet balance ready for airtime, data and bill payments.</p><button className="asf-btn" onClick={() => navigate("/dashboard/wallet")}>Fund wallet <ChevronRight size={16} /></button><small className="wallet-visual-caption">FERIXAS WALLET / READY</small></section><section className="quick-actions"><header><div><span className="eyebrow">QUICK ACTIONS</span><h2>Buy a service</h2></div><button onClick={() => navigate("/dashboard/services")}>View all</button></header>{availableServices.map((service, index) => { const Icon = icons[service.slug]; return <button key={service.slug} onClick={() => navigate(`/dashboard/services/${service.slug}`)}><span>0{index + 1}</span><Icon size={17} /><b>{service.name || service.label || service.title}</b><ChevronRight size={16} /></button>; })}</section><section className="balance-trio"><Balance label="Main balance" value={wallet.main_balance} icon={WalletCards} /><Balance label="Cashback balance" value={wallet.cashback_balance} icon={Gift} /><Balance label="Referral balance" value={wallet.referral_balance} icon={Copy} /></section><section className="recent"><header><div><span className="eyebrow">RECENT TRANSACTIONS</span><h2>Latest activity</h2></div><button onClick={() => navigate("/dashboard/transactions")}>View all</button></header>{transactions.slice(0, 4).map(tx => <TxRow key={tx.id || tx.reference} tx={tx} onClick={() => navigate(`/dashboard/transactions/${tx.id || tx.reference}`)} />)}{!transactions.length && <p className="empty-state">No transaction activity yet.</p>}</section></div></div>;
}

export { ApprovedLiveDashboardHome };
