// Ferixas support workspace: live ticket messages and reply attachments use the existing authenticated customer endpoints.
"use client";

import { ArrowLeft, FileText, MessageCircle, Paperclip, Plus, Send } from "lucide-react";
import { FormEvent, useCallback, useEffect, useRef, useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";
import * as api from "../lib/liveApi";

export default function LiveSupportWorkspace() {
  const [, go] = useLocation(); const [tickets, setTickets] = useState<any[]>([]); const [selected, setSelected] = useState<any>(null); const [messages, setMessages] = useState<any[]>([]); const [newTicket, setNewTicket] = useState({ subject: "", message: "" }); const [reply, setReply] = useState(""); const [files, setFiles] = useState<File[]>([]); const [busy, setBusy] = useState(false); const ticketFileInput = useRef<HTMLInputElement>(null); const replyFileInput = useRef<HTMLInputElement>(null);
  const loadTickets = useCallback(async () => { const next = await api.getTickets(); setTickets(next); if (!selected && next[0]) setSelected(next[0]); }, [selected?.id]);
  const loadMessages = useCallback(async () => { if (!selected?.id) { setMessages([]); return; } setMessages(await api.getTicketMessages(selected.id)); }, [selected?.id]);
  useEffect(() => { void loadTickets(); }, []); useEffect(() => { void loadMessages(); }, [loadMessages]);
  const create = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { const created = await api.createTicket(newTicket.subject, newTicket.message, files); toast.success("Support ticket created."); setNewTicket({ subject: "", message: "" }); setFiles([]); setSelected(created); await loadTickets(); } catch (cause: any) { toast.error(cause.message || "Could not create your ticket."); } finally { setBusy(false); } };
  const send = async (event: FormEvent) => { event.preventDefault(); if (!selected?.id) return; setBusy(true); try { await api.replyTicket(selected.id, reply, files); setReply(""); setFiles([]); await loadMessages(); await loadTickets(); } catch (cause: any) { toast.error(cause.message || "Could not send your reply."); } finally { setBusy(false); } };
  return <main className="support-workspace"><header><button onClick={() => go("/dashboard")}><ArrowLeft size={17} />Dashboard</button><div><small>FERIXAS / ASAFORVTU</small><h1>Support centre</h1></div></header><section className="support-layout"><aside><form className="support-create" onSubmit={create}><h2>New ticket</h2><input placeholder="Subject" value={newTicket.subject} onChange={e => setNewTicket({ ...newTicket, subject: e.target.value })} required /><textarea placeholder="Tell us how we can help" value={newTicket.message} onChange={e => setNewTicket({ ...newTicket, message: e.target.value })} required /><input hidden ref={ticketFileInput} type="file" accept="image/*,video/*,.pdf,.doc,.docx,.txt" multiple onChange={e => setFiles(Array.from(e.target.files || []))} /><button type="button" className="support-attach" onClick={() => ticketFileInput.current?.click()}><Paperclip size={15} />{files.length ? `${files.length} attached` : "Attach file or video"}</button><button className="asf-btn" disabled={busy}><Plus size={15} />Create ticket</button></form><div className="ticket-list"><h2>Your tickets</h2>{tickets.length ? tickets.map(ticket => <button key={ticket.id} className={selected?.id === ticket.id ? "selected" : ""} onClick={() => setSelected(ticket)}><b>{ticket.subject}</b><small>{ticket.status || "open"} · {ticket.created_at ? new Date(ticket.created_at).toLocaleDateString() : ""}</small></button>) : <p>No support tickets yet.</p>}</div></aside><section className="ticket-thread">{selected ? <><header><MessageCircle size={20} /><div><b>{selected.subject}</b><small>{selected.status || "open"}</small></div></header><div className="ticket-messages">{messages.map(message => <article key={message.id} className={message.is_admin ? "admin" : "customer"}><b>{message.is_admin ? "Support" : "You"}</b><p>{message.message}</p>{Array.isArray(message.attachments) && message.attachments.map((attachment: any) => <span key={attachment.id}><FileText size={13} />{attachment.original_name}</span>)}<small>{message.created_at ? new Date(message.created_at).toLocaleString() : ""}</small></article>)}{!messages.length && <p className="empty-state">Your ticket messages will appear here.</p>}</div><form className="ticket-reply" onSubmit={send}><input hidden ref={replyFileInput} type="file" accept="image/*,video/*,.pdf,.doc,.docx,.txt" multiple onChange={e => setFiles(Array.from(e.target.files || []))} /><button type="button" onClick={() => replyFileInput.current?.click()} aria-label="Attach file or video"><Paperclip size={17} /></button><input placeholder="Reply to support" value={reply} onChange={e => setReply(e.target.value)} /><button className="asf-btn" disabled={busy}><Send size={15} /></button></form></> : <div className="empty-thread"><MessageCircle size={34} /><p>Select a ticket to view its conversation.</p></div>}</section></section></main>;
}
