// Ferixas landing: applies the supplied AsaforVTU master copy without changing the established public visual system or guest-to-auth flow.
import "../master-copy.css";
import "../public-reference.css";
import "../public-promos.css";
import RealBannerCarousel from "../components/RealBannerCarousel";
import { ChevronLeft, ChevronRight, FileText, GraduationCap, Headphones, Menu, Phone, ReceiptText, ShieldCheck, Tv, WalletCards, Wifi, X, Zap } from "lucide-react";
import { useState } from "react";
import { useLocation } from "wouter";

const LOGO = "/brand/ferixas-globe.png";
const HERO = "/manus-storage/asaforvtu-signal-ledger-hero_a6a5c86e.png";
const services = [
  [Phone, "Airtime Recharge", "Recharge a mobile number by selecting your network and providing the phone number you want to recharge.", "Buy Airtime"],
  [Wifi, "Data Bundles", "Choose an available data plan for your network and purchase it for your preferred phone number.", "Buy Data"],
  [Zap, "Electricity Bills", "Pay your electricity bill using the required customer or meter information, service details and amount.", "Pay Electricity"],
  [Tv, "Cable TV", "Renew your cable TV subscription by selecting your provider and plan and providing your customer or Smartcard details.", "Renew Subscription"],
  [GraduationCap, "Exam PINs", "Purchase result-checking PINs by selecting your examination type and required quantity.", "Buy Exam PIN"],
] as const;
const benefits = [[WalletCards, "One Wallet", "Manage your wallet and use your available balance to access supported digital services."], [Zap, "Multiple Services", "Access airtime, data, electricity, cable TV and exam PIN services from one platform."], [ReceiptText, "Transaction Records", "Keep track of your transactions, references and receipts from your account."], [Headphones, "Customer Support", "Get assistance with your account and transactions through your support account."]] as const;
const process = [["01", "Create Your Account", "Register for an AsaforVTU account and provide the required information."], ["02", "Verify Your Email", "Verify your email address to activate your account."], ["03", "Fund Your Wallet", "Add funds to your AsaforVTU wallet."], ["04", "Choose a Service", "Select airtime, data, electricity, cable TV or exam PINs."], ["05", "Confirm Your Transaction", "Review your transaction details and confirm using your transaction PIN."], ["06", "Keep Your Receipt", "View your transaction record, reference and receipt from your account."]] as const;

export default function LandingPage() {
  const [, setLocation] = useLocation(); const [open, setOpen] = useState(false); const [walletTab, setWalletTab] = useState(0);
  const go = (route: string) => { setOpen(false); setLocation(route); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const walletTabs = [["Main Balance", "Your primary wallet balance for supported digital service transactions."], ["Cashback Balance", "View your available cashback balance and transfer eligible funds to your main wallet."], ["Referral Balance", "Manage your eligible referral balance and transfer available funds to your main wallet."]] as const;
  return <main className="landing-refined">
    <header className="landing-refined-top"><button className="landing-refined-brand" onClick={() => go("/")}><span><img src={LOGO} alt="Ferixas AsaforVTU" /></span><div><b>Ferixas</b><small>ASAFORVTU</small></div></button><nav className={open ? "open" : ""}><button onClick={() => go("/")}>Home</button><button onClick={() => go("/services")}>Services</button><button onClick={() => go("/how-it-works")}>How It Works</button><button onClick={() => go("/about")}>About Us</button><button onClick={() => go("/updates")}>Updates</button><button onClick={() => go("/help")}>Help</button><button onClick={() => go("/login")}>Sign In</button><button className="landing-refined-cta" onClick={() => go("/register")}>Create Account <ChevronRight size={16}/></button></nav><button className="landing-refined-menu" onClick={() => setOpen(!open)} aria-label="Open navigation">{open ? <X/> : <Menu/>}</button></header>
    <section className="landing-refined-hero"><div><h1>One Wallet for<br/><em>Everyday Top-Up Services</em></h1><p>Fund your wallet and purchase airtime, data, electricity, cable TV and exam PINs from one account.</p><div className="landing-refined-actions"><button className="landing-refined-cta" onClick={() => go("/register")}>Create Your Account <ChevronRight size={16}/></button><button className="landing-refined-text" onClick={() => go("/services")}>Explore Services</button></div></div><RealBannerCarousel /></section>
    <section className="landing-trust-strip"><article><ShieldCheck/><div><b>Secure & Reliable</b><small>Wallet and records protected</small></div></article><article><Zap/><div><b>Fast Service Delivery</b><small>Clear top-up flow</small></div></article><article><Headphones/><div><b>Account Support</b><small>Help when you need it</small></div></article></section>
    <section className="copy-section copy-section--paper"><div className="copy-section__heading"><span>CORE BENEFITS</span><h2>Everything You Need in One Place</h2></div><div className="copy-card-grid copy-card-grid--four">{benefits.map(([Icon,title,copy]) => <article key={title}><Icon/><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    <section className="landing-refined-services"><header><span>OUR SERVICES</span><h2>Essential Digital Services, All in One Place</h2><small>Access the everyday digital services you need through your AsaforVTU account.</small></header><div className="landing-refined-grid">{services.map(([Icon, title, note, action], index) => <button className="landing-route-card landing-route-card--copy" key={title} onClick={() => go("/register")}><span className="landing-refined-index">0{index + 1}</span><span className="landing-refined-service-icon"><Icon size={21}/></span><span className="landing-route-copy"><b>{title}</b><small>{note}</small></span><ChevronRight size={18}/><span className="landing-route-status"><i/>{action}</span></button>)}</div></section>
    <section className="copy-section copy-wallet"><div className="copy-section__heading"><span>YOUR WALLET</span><h2>One Wallet. Multiple Digital Services.</h2><p>Fund your AsaforVTU wallet and use your available balance to access supported digital services from one account.</p></div><div className="copy-wallet__panel"><nav>{walletTabs.map(([title],index)=><button className={walletTab===index?"active":""} onClick={()=>setWalletTab(index)} key={title}>{title}</button>)}</nav><div><WalletCards/><h3>{walletTabs[walletTab][0]}</h3><p>{walletTabs[walletTab][1]}</p><button className="landing-refined-cta" onClick={()=>go("/register")}>Create Your Account <ChevronRight size={16}/></button></div></div></section>
    <section className="copy-section copy-section--paper"><div className="copy-section__heading"><span>HOW IT WORKS</span><h2>Simple From Start to Finish</h2><p>Get started with AsaforVTU in a few simple steps.</p></div><ol className="copy-steps">{process.map(([number,title,copy])=><li key={number}><span>{number}</span><div><h3>{title}</h3><p>{copy}</p></div></li>)}</ol><button className="copy-section__link" onClick={()=>go("/how-it-works")}>See How It Works <ChevronRight size={16}/></button></section>
    <section className="copy-section"><div className="copy-section__heading"><span>TRANSACTION HISTORY</span><h2>Keep Track of Every Transaction</h2><p>Your transaction history keeps your top-up activity organized and accessible from your account.</p></div><div className="copy-card-grid copy-card-grid--four">{[[FileText,"Transaction History","Review your previous transactions."],[ReceiptText,"Transaction References","Keep track of your transaction references."],[ShieldCheck,"Receipts","Keep your transaction records and receipts available for reference."],[WalletCards,"Top-Up Records","Review the details and results of your service purchases."]].map(([Icon,title,copy])=>{const I=Icon as typeof FileText;return <article key={String(title)}><I/><h3>{String(title)}</h3><p>{String(copy)}</p></article>})}</div></section>
    <section className="copy-section copy-section--paper"><div className="copy-section__heading"><span>WHY ASAFORVTU</span><h2>Built for Everyday Top-Up Services</h2><p>AsaforVTU brings essential VTU services together through one wallet-based account.</p></div><div className="copy-why">{[["Multiple Services","Access essential VTU services from one account."],["Wallet-Based Purchases","Fund your wallet and use your available balance for supported top-up services."],["Simple Top-Ups","Choose a service, enter the required details and confirm."],["Visible Records","Keep track of your transactions, references and receipts."],["Rewards Balances","View eligible cashback and referral balances."],["Account Support","Get help through your account when you need assistance."]].map(([title,copy],index)=><article key={title}><span>0{index+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    <section className="copy-section copy-ferixas"><div className="copy-section__heading"><span>POWERED BY FERIXAS</span><h2>Technology Built to Solve Real Problems</h2></div><div><p>Ferixas is a technology company focused on creating practical digital products and solutions that solve real-world problems for people, businesses and organizations.</p><p>We build technology around real needs, starting from local opportunities and developing products with the potential to serve users and businesses beyond them.</p><p>AsaforVTU is one of the products developed by Ferixas, currently focused on making everyday top-up services easier for customers in Nigeria.</p><button className="copy-section__link" onClick={()=>go("/about")}>About AsaforVTU <ChevronRight size={16}/></button></div></section>
    <section className="copy-section copy-support"><div><span>CUSTOMER SUPPORT</span><h2>We're Here When You Need Help</h2><p>Have a question about your account or transaction? Create a support ticket, follow your conversation and get assistance through your account.</p></div><div><button className="landing-refined-cta" onClick={()=>go("/login")}>Get Support <ChevronRight size={16}/></button><button className="landing-refined-text" onClick={()=>go("/help")}>Visit Help Center</button></div></section>
    <section className="copy-section copy-updates"><div className="copy-section__heading"><span>LATEST UPDATES</span><h2>Stay Up to Date</h2><p>Stay informed about AsaforVTU announcements, service availability, maintenance and platform updates.</p></div><article><h3>No Updates Available</h3><p>There are no new updates at the moment. Check back later for important announcements.</p><button className="copy-section__link" onClick={()=>go("/updates")}>View All Updates <ChevronRight size={16}/></button></article></section>
    <section className="copy-final"><h2>Your Everyday Top-Up Services Start Here</h2><p>Create your AsaforVTU account, fund your wallet and buy the services you need from one platform.</p><div><button className="landing-refined-cta" onClick={()=>go("/register")}>Create Your Account <ChevronRight size={16}/></button><button className="landing-refined-text" onClick={()=>go("/services")}>Explore Services</button></div><small>Already have an account? <button onClick={()=>go("/login")}>Sign In</button></small></section>
    <footer className="landing-refined-footer landing-refined-footer--master"><div className="landing-footer-brand"><span><img src={LOGO} alt="Ferixas AsaforVTU"/></span><div><b>Ferixas</b><small>ASAFORVTU</small></div><p>AsaforVTU is Ferixas' wallet-based platform for buying airtime, data, electricity, cable TV and exam PINs in Nigeria.</p></div><div><strong>PLATFORM</strong><small>Home · Services · How It Works · Updates · Help Center</small></div><div><strong>COMPANY</strong><small>About Us · Contact Us</small></div><div><strong>ACCOUNT</strong><small>Create Account · Sign In</small></div><nav><button onClick={() => go("/privacy")}>Privacy Policy</button><button onClick={() => go("/terms")}>Terms of Service</button><button onClick={() => go("/refund-policy")}>Refund Policy</button></nav><p>© 2026 Ferixas. All rights reserved. <span>AsaforVTU is a product of Ferixas.</span></p></footer>
  </main>;
}
